Adds better pre-commit script which also corrects files

diff --git a/git/pre-commit b/git/pre-commit
--- a/git/pre-commit
+++ b/git/pre-commit
@@ -1,13 +1,49 @@
 # paste this into your project's .git/hooks/pre-commit file
-require 'rubocop'
+# make file executable after saving: chmod +x .git/hooks/pre-commit
 
-changed_files = `git status --porcelain`.split(/\n/).
-    map { |file_name_with_status|
-      file_name_with_status.split(' ')[1]
-    }.
-    select { |file_name|
-      File.extname(file_name) == '.rb'
-    }.join(' ')
-system("rubocop #{changed_files} -c ~/.rubocop.yml") unless changed_files.empty?
+#!/bin/sh
+#
+# Check for ruby style errors
 
-exit $CHILD_STATUS.to_s[-1].to_i
+red='\033[0;31m'
+green='\033[0;32m'
+yellow='\033[0;33m'
+NC='\033[0m'
+
+if git rev-parse --verify HEAD >/dev/null 2>&1
+then
+	against=HEAD
+else
+	# Initial commit: diff against an empty tree object
+	# Change it to match your initial commit sha
+	against=123acdac4c698f24f2352cf34c3b12e246b48af1
+fi
+
+# Check if rubocop is installed for the current project
+bin/bundle exec rubocop -v >/dev/null 2>&1 || { echo >&2 "${red}[Ruby Style][Fatal]: Add rubocop to your Gemfile"; exit 1; }
+
+# Get only the staged files
+FILES="$(git diff --cached --name-only --diff-filter=AMC | grep "\.rb$" | tr '\n' ' ')"
+
+echo "${green}[Ruby Style][Info]: Checking Ruby Style${NC}"
+
+if [ -n "$FILES" ]
+then
+	echo "${green}[Ruby Style][Info]: ${FILES}${NC}"
+	
+	if [ ! -f '.rubocop.yml' ]; then
+	  echo "${yellow}[Ruby Style][Warning]: No .rubocop.yml config file.${NC}"
+	fi
+	
+	# Run rubocop on the staged files
+	bin/bundle exec rubocop ${FILES} -a
+	
+	if [ $? -ne 0 ]; then
+	  echo "${red}[Ruby Style][Error]: Fix the issues and commit again${NC}"
+	  exit 1
+	fi
+else
+	echo "${green}[Ruby Style][Info]: No files to check${NC}"
+fi
+
+exit 0
